### ISSUE TITLE
Error handling with ETH connections mishaps

### ISSUE THREAD

**Issue by strazzere** [polyswarm/polyswarmd#14]
The function `check_transactions` is used extensively in `bounties.py` - which by default is utilizing a 120 second timeout when trying to chat with eth. This has had some weird results which a microengine I've been working on. Outside of a few other bugs I need to submit (where the eth is throwing 404s, etc) this unanticipated exception being thrown after a long period of time causes some RESTful api woes;

https://github.com/polyswarm/polyswarmd/blob/master/src/polyswarmd/eth.py#L58-L60

This function is what will hold up multiple RESTful calls in `bounties.py`. Potentially the should set the timeout for more aggressively than the default `120` seconds. Something around ~5 or so seems sane? The default wait time for the microengines (based on the examples) is ~10 seconds.

I'd also propose that the above functionality should catch a timeout assertion and pass it as a failure for the transaction? Though I'm unsure this is the proper way to handle it. Potentially the `POST /bounties` end points should tell a microengine it is still processing? Whether via a status code change to `HTTP 102 Processing` or maybe a `200` with a status field?

Error log from running `dockercompose -f dev.yml -f test.yml up` while running a microengine to post assertions at the same time;'
```
polyswarmd_1  | 2018-07-04 19:18:05.770838 POST /artifacts
polyswarmd_1  | 2018-07-04 19:18:05.788637 POST /artifacts
polyswarmd_1  | 2018-07-04 19:18:05.803471 POST /bounties
polyswarmd_1  | [2018-07-04 19:20:05,848] ERROR in app: Exception on /bounties [POST]
polyswarmd_1  | Traceback (most recent call last):
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/flask_sockets.py", line 40, in __call__
polyswarmd_1  |     handler, values = adapter.match()
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
polyswarmd_1  |     raise NotFound()
polyswarmd_1  | werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
polyswarmd_1  | 
polyswarmd_1  | During handling of the above exception, another exception occurred:
polyswarmd_1  | 
polyswarmd_1  | Traceback (most recent call last):
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
polyswarmd_1  |     response = self.full_dispatch_request()
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
polyswarmd_1  |     rv = self.handle_user_exception(e)
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
polyswarmd_1  |     reraise(exc_type, exc_value, tb)
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
polyswarmd_1  |     raise value
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
polyswarmd_1  |     rv = self.dispatch_request()
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
polyswarmd_1  |     return self.view_functions[rule.endpoint](**req.view_args)
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/polyswarmd/bounties.py", line 131, in post_bounties
polyswarmd_1  |     if not check_transaction(web3, tx):
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/polyswarmd/eth.py", line 59, in check_transaction
polyswarmd_1  |     receipt = web3.eth.waitForTransactionReceipt(tx)
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/web3/eth.py", line 199, in waitForTransactionReceipt
polyswarmd_1  |     return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/web3/utils/transactions.py", line 58, in wait_for_transaction_receipt
polyswarmd_1  |     _timeout.sleep(poll_latency)
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/web3/utils/threads.py", line 68, in sleep
polyswarmd_1  |     self.check()
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/web3/utils/threads.py", line 61, in check
polyswarmd_1  |     raise self
polyswarmd_1  | web3.utils.threads.Timeout: 120 seconds
polyswarmd_1  | 2018-07-04 19:20:06.872169 POST /bounties
polyswarmd_1  | [2018-07-04 19:22:06,931] ERROR in app: Exception on /bounties [POST]
polyswarmd_1  | Traceback (most recent call last):
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/flask_sockets.py", line 40, in __call__
polyswarmd_1  |     handler, values = adapter.match()
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/werkzeug/routing.py", line 1581, in match
polyswarmd_1  |     raise NotFound()
polyswarmd_1  | werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
polyswarmd_1  | 
polyswarmd_1  | During handling of the above exception, another exception occurred:
polyswarmd_1  | 
polyswarmd_1  | Traceback (most recent call last):
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
polyswarmd_1  |     response = self.full_dispatch_request()
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
polyswarmd_1  |     rv = self.handle_user_exception(e)
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
polyswarmd_1  |     reraise(exc_type, exc_value, tb)
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
polyswarmd_1  |     raise value
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
polyswarmd_1  |     rv = self.dispatch_request()
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
polyswarmd_1  |     return self.view_functions[rule.endpoint](**req.view_args)
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/polyswarmd/bounties.py", line 131, in post_bounties
polyswarmd_1  |     if not check_transaction(web3, tx):
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/polyswarmd/eth.py", line 59, in check_transaction
polyswarmd_1  |     receipt = web3.eth.waitForTransactionReceipt(tx)
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/web3/eth.py", line 199, in waitForTransactionReceipt
polyswarmd_1  |     return wait_for_transaction_receipt(self.web3, transaction_hash, timeout)
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/web3/utils/transactions.py", line 58, in wait_for_transaction_receipt
polyswarmd_1  |     _timeout.sleep(poll_latency)
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/web3/utils/threads.py", line 68, in sleep
polyswarmd_1  |     self.check()
polyswarmd_1  |   File "/usr/local/lib/python3.6/site-packages/web3/utils/threads.py", line 61, in check
polyswarmd_1  |     raise self
polyswarmd_1  | web3.utils.threads.Timeout: 120 seconds
```

**Comment by strazzere** [comment]
This can be closed as `check_transaction` has been removed and it seems like the end points will just return the transactions vs waiting for the completion
